### ISSUE TITLE
运行web_server.py时出现No module named 'data_read'

### ISSUE THREAD

**Issue by sxk000** [EricLingRui/NLP-tools#2]
您好！本项目代码是不完整吗？我在安装说明运行web_server.py时出现No module named 'data_read'问题，原以为是缺少第三方data_read包，但是我pip3 install data_read时却没有找到这个包，这个包是自己定义的吗？ 本项目代码是不完整吗？
python3 web_server.py
WARNING:tensorflow:From /usr/local/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/datasets/base.py:198: retry (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
Instructions for updating:
Use the retry module or similar alternatives.
Traceback (most recent call last):
  File "web_server.py", line 5, in <module>
    import data_read as readData
ModuleNotFoundError: No module named 'data_read'

**Comment by EricLingRui** [comment]
data_read本为最初的训练集预处理文件，后为了区分不同的训练集，将其替换为data_read_（训练类型）_（来源名）的文件。其中，data_read_pos_RMRB.py为以人民日报为语料集，将其预处理词性训练的文件，data_read_seg_RMRB.py 为以人民日报为语料集，将其处理成训练分词模型的数据集。另外，模型是需要训练的，其中data_read模块都需要替换到指定任务（分词或者词性标注）。
