### ISSUE TITLE
你好，训练时，如何区分不同的任务呀，pos/分词？

### ISSUE THREAD

**Issue by lqfarmer** [EricLingRui/NLP-tools#3]
如题

**Comment by EricLingRui** [comment]
不好意思，现在才看到问题。分词和pos任务在模型中都是以序列形式训练，因此不需要区分。只用按你的任务对应相应的标签即可。
分词的输入格式：
![image](https://user-images.githubusercontent.com/26210791/46065537-df4d9100-c1a4-11e8-9be9-4e84617f1000.png)
词性的输入格式：
![image](https://user-images.githubusercontent.com/26210791/46065558-f2f8f780-c1a4-11e8-9ae0-1dc0317e6d78.png)

**Comment by hongweijun811** [comment]
你好  我想请问一下训练模型需要多大的内存，服务器有100多G好像还是不够？另外test文件下怎么没有jyaq.csv文件？只有词性标注的测试文件吗？
