### ISSUE TITLE
你好 我想请问一下训练模型需要多大的内存，服务器有100多G好像还是不够？另外test文件下怎么没有jyaq.csv文件？只有词性标注的测试文件吗？

### ISSUE THREAD

**Issue by hongweijun811** [EricLingRui/NLP-tools#4]
你好 我想请问一下训练模型需要多大的内存，服务器有100多G好像还是不够？另外test文件下怎么没有jyaq.csv文件？只有词性标注的测试文件吗？

**Comment by EricLingRui** [comment]
由于之前模型比较乱，现在更新了下。

**Comment by hongweijun811** [comment]
请问命名实体识别方面是能够识别出哪些实体？人民日报的数据应该是没有标记实体的把？这部分您是怎么实现的？

**Comment by EricLingRui** [comment]
> 实体

实体类型由训练得到。人民日报未标注实体，不过可以简单认为其词性t对应实体时间TIME。依次类推。不过理论上这不是相等关系。我所训练的实体识别是通过数据库回标或者手工标记产生的训练集。
