### ISSUE TITLE
???

### ISSUE THREAD

**Issue by lili1234567890** [EricLingRui/NLP-tools#6]
File "train.py", line 125, in main
    model = modelDef.BiLSTMModel(max_len=data.max_len, vocab_size=data.word2id.__len__(), class_num= data.tag2id.__len__(), model_save_path=FLAGS.ckpt_path, embed_size=FLAGS.embed_size, embed_size=FLAGS.layer_num, hidden_size=FLAGS.hidden_size)
TypeError: __init__() got an unexpected keyword argument 'layer_num'

每次都显示没有embed_size、layer_num、或者 hidden_size，是为什么

**Comment by EricLingRui** [comment]
模型已更新，之前比较乱
