### ISSUE TITLE
好像代码有一点不全

### ISSUE THREAD

**Issue by curryli** [EricLingRui/NLP-tools#7]
感谢楼主，基本跑通了。
还想请问一下训练分词和词性标注用的是同一套程序吗？我跑了一下，发现目前代码训练是分词的，测试代码是词性标注的好像?cws_pos

**Comment by EricLingRui** [comment]
代码已经更新

**Comment by VincentLee-EN** [comment]
我也觉得代码好像不全，请问楼主更新代码的地址在哪里呀
