### ISSUE TITLE
训练数据集时报错

### ISSUE THREAD

**Issue by VincentLee-EN** [EricLingRui/NLP-tools#8]
你好！为啥我运行train.py报错了呢？

错误如下：
![image](https://user-images.githubusercontent.com/31602981/53860176-1a3cd600-401b-11e9-8021-1eb1a5a89502.png)

**Comment by virginiadb** [comment]
这个我知道，你的训练data和dict没生成

**Comment by VincentLee-EN** [comment]
谢谢，问题解决了！

请问答主方便告知我你的联系方式（比如微信或者常用邮箱）吗？我其实还有几个问题，希望能和你进一步交流~

我的邮箱：2392539432@qq.com

**Comment by virginiadb** [comment]
好的好的，我也是新手，邮件已发，大家互相交流。

**Comment by LittleStars666** [comment]
@virginiadb 老哥，我能加你QQ吗，我遇到一点问题，想请教你一下，非常感谢
